### ISSUE TITLE
instruct bot to leave channel

### ISSUE THREAD

**Issue by whitewhidow** [jclg/php-slack-bot#1]
Hi, could you include a way of instructing the bot to leave a particular channel.

(when i started the bot it joined a channel wich i did not want it to join ... )

Regards.

Sam

**Comment by jclg** [comment]
Hello Sam,

I think it's possible using the channel.leave api method.
https://api.slack.com/methods/channels.leave

At the moment, the bot listens on all public channels.
It receives all events from the message server https://api.slack.com/rtm
I think I will add a way to configure an array of channels the bot can join.

**Comment by whitewhidow** [comment]
are you sure it listens on EVERY public channel, it seemed like it was only listening on the channels it had actually joined (either the default one it joined when creating it, or ones it was invited too),   this is what i would expect, i would not want it to listen/reply to public channels it is not in ...

anyways, about the channels, i was thinking something similar, perhaps just a whitelist or blacklist of channels ...   (in my case a blacklist would have been usefull)

my main issue was, upon setting up the bot, it joined the 1 single channel, in wich we really dont allow bots in our company, and now i dont have a way of having the bot leave the channel   (so i currently blocked it in the code, if the channel id matched that one)

Also, structure wise,   if i pull you stuff in via composer, and implement them in my project, there is no way (currently in your setup), for me to add commands, without having to edit files in YOUR package ..
(so now if i pull your updates, my stuff is gone
It would be much more usefull if there was a way of adding commands, by only adding files, and possibly editing an unmanaged config file, so that your files can stay intact    (ill have a go at all this, this weekend)

**Comment by jclg** [comment]
After some tests, you can remove the bot from a channel, the same way you remove a normal user.
https://slack.zendesk.com/hc/en-us/articles/201898668-Removing-someone-from-a-channel
It seems that it's not possible to remove the bot from the default channel #general

Please let me know if it works for you.

I also added a public method to load your own commands. More information in the README.

**Comment by maxadamo** [comment]
This doesn't work for me. 
I am primary owner of workspace, and I tried kick/remove without success
