### ISSUE TITLE
Webhooks doesn't work due to getPost method missing in react Request class

### ISSUE THREAD

**Issue by shivas** [jclg/php-slack-bot#10]
I guess it's version issue

**Comment by jclg** [comment]
Hello,

Thank you for reporting this issue.

Yes, it seems to be a version issue https://github.com/reactphp/http/issues/61
I will try to fix it next week.

**Comment by jclg** [comment]
Add the following line in your composer.json

`"react/http": "dev-master#cd15204bd15d106d7832c680e4fb0ca0ce2f5e30"`

So you will have something like this in your file

``` javascript
{
    "minimum-stability" : "dev",
    "require": {
        "jclg/php-slack-bot": "dev-master",
        "react/http": "dev-master#cd15204bd15d106d7832c680e4fb0ca0ce2f5e30"
    }
}
```

Then, run **composer update**
Composer should checkout the correct commit with the getPost() method.

Please let me know if it works for you.

**Comment by jclg** [comment]
https://github.com/jclg/php-slack-bot/commit/737d15297d97aa298bb26407c1649a53a3a00c0f
