### ISSUE TITLE
multiple catch all commands

### ISSUE THREAD

**Issue by djdevin** [jclg/php-slack-bot#13]
Multiple catch all commands would be nice. We have a couple bots that do regex on messages.

**Comment by djdevin** [comment]
Additionally it might be nice to not disable all other commands (useful in terms of organizing "commands" vs. "listeners" ).

**Comment by jclg** [comment]
Hi

Thank you for the PR.
Do you think the "catch all command" term is meaningful enough ? Maybe something like "event" is clearer.

**Comment by djdevin** [comment]
It made sense to me. 

For inspiration: I just took a look at api.ai today and they described their slack integration this way:

Direct message. The bot can receive a direct message from a user.
Direct mention. The bot can be mentioned at the beginning of a message.
Mention. The bot can be mentioned in any part of a message.
Ambient. The bot can hear any message in a channel.

So maybe

Command = mentionListener
Catch all = ambientListener
