### ISSUE TITLE
What might come back to $data?

### ISSUE THREAD

**Issue by kpaxman** [jclg/php-slack-bot#18]
Is there documentation anywhere about what possible information might come back as $data?

**Comment by jclg** [comment]
Yes, you can find the documentation here https://api.slack.com/rtm

**Comment by kpaxman** [comment]
I think I've figured it out.

So I should be looking at the message event - https://api.slack.com/events/message - for what would be returned as $data when a message is posted in the channel.

The keys will vary depending on the message subtype. For example, if you want to know what messages from bots look like, you need to look at the bot_message subtype (https://api.slack.com/events/message/bot_message).

Have I interpreted this correctly?

**Comment by jclg** [comment]
Yes, you are correct.
