### ISSUE TITLE
Only respond to mentions?

### ISSUE THREAD

**Issue by syropian** [jclg/php-slack-bot#23]
Is there a way to get the bot to only run commands when mentioned? Is adding the bots username to the command name enough?

ie instead of just typing `doThing` in slack I want to have to type `@mybot doThing`

**Comment by jclg** [comment]
Yes, I just added this option in version 0.0.4

In your command class, you have to use the setMentionOnly method

```php
    protected function configure() {
        $this->setName('doThing');
        $this->setMentionOnly(true);
    }
```

This is a new feature so please let me know if it works for you ;)
