### ISSUE TITLE
Case-insensitive command

### ISSUE THREAD

**Issue by vleonov** [jclg/php-slack-bot#28]
Current implemenation of Command is case-sensitive. E.g. if I register a command `help`, I should send exact command `help`, but not `Help` or `HELP`. It's unusual.

So, why don't make it case-insensitive by adding modifier `i` inside `getCommand` method?

This
`$find = '/^'.preg_quote($commandName).'/';`
Change to this
`$find = '/^'.preg_quote($commandName).'/i';`

**Comment by jclg** [comment]
I don't think it's unusual but maybe we can make it optional.
Inside the configure() method for a given command, we can set this option.
By default, it's still case-sensitive.

```php
    protected function configure() {
        $this->setName('help');
        $this->setCaseInsensitive(true); // Now it works with help, Help and HELP
    }
```

What do you think ?

**Comment by vleonov** [comment]
Well, why not? This solution would work fine.
