### ISSUE TITLE
Bot is not working

### ISSUE THREAD

**Issue by CanGokdere** [jclg/php-slack-bot#3]
I have been trying to debug but got no results. Bot is successfully getting wsurl but I think it is not connecting to the wsurl (No log indicating it has connected), also it does not respond to any command. Also the php script terminates after around 30 seconds of run time. What might be the problem ?

**Comment by jclg** [comment]
Hello Can,

You have to run the script from the command line.

Here are the instructions step by step :

First you have to create a composer.json file with the following :

```
{
    "minimum-stability" : "dev",
    "require": {
        "jclg/php-slack-bot": "dev-master"
    }
}
```

Then, run **composer install**
This will download all required dependencies.

Create a new bot.php file with :

```
<?php
require 'vendor/autoload.php';
use PhpSlackBot\Bot;


$bot = new Bot();
$bot->setToken('xoxb-**************');
$bot->run();
```

Make sure to insert your token.

At this step, you sould have the following files inside your project folder :
- bot.php
- composer.json
- composer.lock
- vendor (directory)

Finally run **php bot.php** from the command line.
Inside Slack, the bot shoud be online (green dot).

Direct message him by tiping ping and the bot should answer "pong".

Please let me know if it works.

**Comment by matthanley** [comment]
For future users: this can happen if you haven't set a default timezone in PHP or if DNS requests to 8.8.8.8 time out (this is called in React's DNS resolver).
